import Constants from "expo-constants";

const ACOOUNT_BASE = `account/`
const BUYER_BASE = `buyer/`
const VENDOR_BASE = `vendor/`
const RIDER_BASE = `rider/`
const ADMIN_BASE = `admin/`
const INVENTORY_BASE = `inventory/`
const CART_BASE = `cart/`
const PAYMENT_BASE = `payment/`
const ENDPOINTS = {
    'account': {
        'profession': `${ACOOUNT_BASE}professions`,
        'chats': `${ACOOUNT_BASE}chats`,
        'chats-create': `${ACOOUNT_BASE}chats/create`,
        'send-message': `${ACOOUNT_BASE}chats/message/send`,
        'list-devices': `${ACOOUNT_BASE}devices/list`,
        'geocode': `${ACOOUNT_BASE}geocode/search`,
        'geocode-decode': `${ACOOUNT_BASE}geocode/decode`,
        'avatar': `${ACOOUNT_BASE}avatar`,
        'transaction-pin': `${ACOOUNT_BASE}transaction/pin`,
        'forgot-transaction-pin': `${ACOOUNT_BASE}transaction/forget`,
        'reset-transaction-pin': `${ACOOUNT_BASE}transaction/reset`,
        'support': `${ACOOUNT_BASE}support`,
    },
    'buyer': { 
        'signin': `${BUYER_BASE}signin`,
        'signup': `${BUYER_BASE}signup`,
        'verify': `${BUYER_BASE}`,
        'user-data':`${BUYER_BASE}data`,
        'search-user': `${BUYER_BASE}users/search`,
        'create-address': `${BUYER_BASE}address/create`,
        'update-address': `${BUYER_BASE}address/update`,
        'buyer-address': `${BUYER_BASE}buyer-address/update`,
        'forget-password': `${BUYER_BASE}password/forget`,
        'validate-password-reset': `${BUYER_BASE}password/validate-otp`,
        'reset-password': `${BUYER_BASE}password/reset`,
        'add-remove-favourite-store': `${BUYER_BASE}store/`,
        'information': `${BUYER_BASE}information`,
        'notification': `${BUYER_BASE}notification`,
        'review': `${BUYER_BASE}review`,
    },
    'vendor': {
        'signin': `${VENDOR_BASE}signin`,
        'signup': `${VENDOR_BASE}signup`,
        'verify': `${VENDOR_BASE}`,
        'user-data':`${VENDOR_BASE}data`,
        'onboard': `${VENDOR_BASE}profile/create`,
        'availability': `${VENDOR_BASE}profile/availability`,
        'forget-password': `${VENDOR_BASE}password/forget`,
        'validate-password-reset': `${VENDOR_BASE}password/validate-otp`,
        'reset-password': `${VENDOR_BASE}password/reset`,
        'list': `${VENDOR_BASE}list`,
        'profile': `${VENDOR_BASE}store`,
        'store-list': `${VENDOR_BASE}store/list`,
        'dashboard': `${VENDOR_BASE}dashboard`,
        'review': `${VENDOR_BASE}review`,
        'create-address': `${VENDOR_BASE}address/create`,
        'update-address': `${VENDOR_BASE}address/update`,
        'information': `${VENDOR_BASE}information`,
        'notification': `${VENDOR_BASE}notification`,
    },
    'rider': {
        'signin': `${RIDER_BASE}signin`,
        'signup': `${RIDER_BASE}signup`,
        'verify': `${RIDER_BASE}`,
        'onboard': `${RIDER_BASE}onboard`,
        'onboard-2': `${RIDER_BASE}onboard-2`,
        'identity': `${RIDER_BASE}identity`,
        'bank-details': `${RIDER_BASE}bank-details`,
        'availability': `${RIDER_BASE}availability`,
        'user-data':`${RIDER_BASE}data`,
        'relationship':`${RIDER_BASE}relationship`,
        'vehicle-type':`${RIDER_BASE}vehicle-type`,
        'toggle-active-status': `${RIDER_BASE}active-status/toggle`,
        'task':`${RIDER_BASE}task`,
        'notification': `${RIDER_BASE}notification`,
        'delete': `${RIDER_BASE}delete`,
        'profile': `${RIDER_BASE}profile`,
    },
    'admin': {
        'signin': `${ADMIN_BASE}signin`,
        'update-support': `${ADMIN_BASE}support/update`,
        'buyers': `${ADMIN_BASE}buyers`,
        'vendors': `${ADMIN_BASE}vendors`,
        'riders': `${ADMIN_BASE}riders`,
        'admins': `${ADMIN_BASE}admins`,
    },
    'inventory': {
        'categories': `${INVENTORY_BASE}categories`,
        'create-meal': `${INVENTORY_BASE}meal/create`,
        'meal-list': `${INVENTORY_BASE}meal/list`,
        'meal': `${INVENTORY_BASE}meal/`,
        'special-offer-meal-list': `${INVENTORY_BASE}meal/list/special-offer`,
        'vendor-meal-list': `${INVENTORY_BASE}meal/list/vendor`,
        'kitchen-meal': `${INVENTORY_BASE}meal/`,
        'delete-meal': `${INVENTORY_BASE}meal/delete`,
    },
    'cart': {
        'add': `${CART_BASE}add`,
        'remove': `${CART_BASE}remove`,
        'list': `${CART_BASE}list`,
        'edit': `${CART_BASE}edit`,
        'checkout': `${CART_BASE}checkout`,
        'checkout-summary': `${CART_BASE}checkout/summary`,
        'buyer-orders': `${CART_BASE}buyer/orders`,
        'buyer-confirm-order': `${CART_BASE}buyer/orders/confirm`,
        'vendor-orders': `${CART_BASE}vendor/orders`,
        'orders-history': `${CART_BASE}order_history`,
    },
    'payment': {
        'buyer-create': `${PAYMENT_BASE}buyer/card/create`,
        'wallet-dashboard': `${PAYMENT_BASE}buyer/wallet/dashboard`,
        'fund-wallet': `${PAYMENT_BASE}buyer/wallet/fund`,
        'pay': `${PAYMENT_BASE}buyer/pay`,
        'banks': `${PAYMENT_BASE}banks`,
        'account-validate': `${PAYMENT_BASE}account/validate`,
        'initialize': `${PAYMENT_BASE}initialize`,
        'vendor-transactions': `${PAYMENT_BASE}transaction/vendor`,
        'rider-transactions': `${PAYMENT_BASE}transaction/rider`,
    },
}

export default ENDPOINTS;